spring.application.name=CrudJspFormat
spring.datasource.url=jdbc:postgresql://localhost:5432/crud_jsp
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=3333
spring.mvc.view.prefix=/CrudJspFormat/src/main/resources/templates
spring.mvc.view.suffix=.html